name: Reusable Backend CI
 
on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
 
permissions:
  contents: read
 
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
 
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
 
      - name: Install and Test
        run: |
          echo "Ejecutando tests de backend..."
          # npm ci
          # npm test
 
