workflow_call:
Name: Reusable Backend Examen

On:
  Workflow_call:
    Inputs:
      Node-version:
        Required: true
        Type: string

Permissions:
  Contents: read

Jobs:
  Build-and-test:
    Runs-on: ubuntu-latest
    Steps:
Name: Checkout repository
        Uses: actions/checkout@v4.1.1 #

Name: Setup Node.js
        Uses: actions/setup-node@v4.0.2
        With:
          Node-version: ${{ inputs.node-version }}
          Cache: ‘npm’ # Optimización (Ejercicio 3)

Name: Install and Test
        Run: |
          Echo “Ejecutando tests de backend…”
          # npm ci
          # npm test
